# Generated by Django 5.1.2 on 2024-10-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=50)),
                ('id_externo', models.CharField(max_length=50)),
                ('data_participacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
