# Generated by Django 5.1.2 on 2024-10-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='incoerente',
            field=models.BooleanField(default=False),
        ),
    ]
