# Generated by Django 5.0.8 on 2024-08-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sorteado',
            field=models.BooleanField(default=False),
        ),
    ]
