# Generated by Django 5.0.8 on 2024-08-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_sorteado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ticket',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
