# Generated by Django 5.0.8 on 2024-08-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_cpf_cliente_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
