# Generated by Django 5.0.8 on 2024-08-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_rename_ticket_cliente_tickets_cliente_id_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tickets',
            new_name='ticket',
        ),
    ]
