# Generated by Django 5.0.8 on 2024-08-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_rename_tickets_cliente_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.CharField(max_length=255),
        ),
    ]
