# Generated by Django 5.0.8 on 2024-08-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_cliente_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_fundo', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
            ],
        ),
    ]
