# Generated by Django 5.0.8 on 2024-08-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_configuracaosite'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='termos_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='termos/'),
        ),
    ]
